### ISSUE TITLE
Server utility not finding import and also getting error "[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'request')"

### ISSUE THREAD

**Issue by rasmuslian** [Baroshem/nuxt-medusa#16]
### Version

nuxt-medusa ^0.3.2
nuxt: ^3.2.3

### Steps to reproduce
Nuxt config:
```
export default defineNuxtConfig({
  modules: ["nuxt-medusa"],
  medusa: {
    server: true,
    global: true,
  },
});
```

### What is Expected?
That `serverMedusaClient` can be used as in the documentation in server routes.

### What is actually happening?
Using this code within 'server/api/products/index.ts'
```
import { serverMedusaClient } from '#medusa/server'
export default eventHandler(async (event) => {
  const client = serverMedusaClient(event)
  const { products } = await client.products.list()
  return { products }
})
```

Gives this result:

`import { serverMedusaClient } from '#medusa/server'` shows the error:
"Cannot find module '#medusa/server' or its corresponding type declarations"

It seems that it cannot find the type declarations, but not only that, when using it (ignoring this error, since it should only by typescript related) I get the following error:

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'request')                                                              15:52:07  
  at dispatchHttpRequest (/D:/Code/solsting/.nuxt/dev/index.mjs:2007:26)
  at new Promise (<anonymous>)
  at httpAdapter (/D:/Code/solsting/.nuxt/dev/index.mjs:1831:11)
  at dispatchRequest (/D:/Code/solsting/.nuxt/dev/index.mjs:2379:10)
  at Axios$1.request (/D:/Code/solsting/.nuxt/dev/index.mjs:2694:15)
  at C.wrap [as axiosClient] (/D:/Code/solsting/.nuxt/dev/index.mjs:655:15)
  at C.request (/D:/Code/solsting/.nuxt/dev/index.mjs:3904:2269)
  at Z.list (/D:/Code/solsting/.nuxt/dev/index.mjs:3904:9050)
  at /D:/Code/solsting/.nuxt/dev/index.mjs:3917:46
  at /D:/Code/solsting/node_modules/h3/dist/index.mjs:1138:14
```

Using `useMedusaClient` works like expected.

**Comment by Baroshem** [comment]
Hey hey,

The first problem you mentioned is TS related, dont need to worry about that :)

The second one I am more concerned.

Could you show me how are you using the event handler registered here`server/api/products/index.ts`?

Are you using `useFetch` or something else?

**Comment by rasmuslian** [comment]
> The first problem wont be so easy to solve as this type of declaration is a recurring situation in several modules.
> 
> The second problem. Why are you using scoped on the script tag? I dont think it is needed :)

The scoped tag got added there accidentally, removed it now and still same error! :)

**Comment by Baroshem** [comment]
@rasmuslian 

Could you create a stackblitz link with reproduction? This is really strange

**Comment by rasmuslian** [comment]
> @rasmuslian
> 
> Could you create a stackblitz link with reproduction? This is really strange

Here is a stackblitz I created now: https://stackblitz.com/edit/nuxt-starter-ezqx4d

**Comment by Baroshem** [comment]
I see.

Thanks for that. I know where the problem is. This is really strange one. I will publish a new version in the upcoming hours that should fix that :)

**Comment by Baroshem** [comment]
Hey, can you try the 0.3.4 version? It should be working there. I also need to correct the docs :)

**Comment by rasmuslian** [comment]
> Hey, can you try the 0.3.4 version? It should be working there. I also need to correct the docs :)

It's working now with version 0.3.4! :) What was the issue?
