### ISSUE TITLE
 I'm having error though, when running in ssr mode: '[nuxt] [request error] [unhandled] [500] Cannot find module './lib/axios'   

### ISSUE THREAD

**Issue by SaulAbreu** [Baroshem/nuxt-medusa#31]
### Version

nuxt-medusa 
nuxt:

**Comment by fsyntax** [comment]
Experiencing the same here on fresh projects. 
I did notice that the most recent version of the medusa-js client is `^6.0.2` - compared to the version in this module (`^1.3.10`)

**Comment by SaulAbreu** [comment]
The error was I set the NITRO PORT to 8000 as env variable in Netlify, when is it not needed.

**Comment by fsyntax** [comment]
How does that even relate? For me this is happening on a local environment, fresh Nuxt 3 install..

**Comment by fsyntax** [comment]
Thanks for the advice, but the medusa config itself is fine. When working with the `@medusajs/medusa-js` client itself, it's working. Hence my note about the client version in the module

**Comment by dimitrio-m** [comment]
Hello! I'm currently having the same issue after starting a fresh project. I followed [this guide](https://medusajs.com/blog/nuxt-medusa-module/) and got the same error as the title of the issue. Do you guys know about a workaround or something?

**Comment by Baroshem** [comment]
Hey,

I have encountered this issue some time ago but now it disapeared and was not occuring anymore. The problem I had was related to client vs browser usage of this package. When I have implemented one solution it was breaking the other one. So I decided to stay with the current one as it was not causing any problems for me. I will reopen this issue and try to experiment in the upcoming days but I will be also working on other packages so if anyone would be up for doing some reasearch please do so :)

**Comment by dimitrio-m** [comment]
@Baroshem I'm a noob with anything related to open source and npm packaging, but I think it has something to do with the npm package configuration. I tested it locally and it works great. I also linked the module locally from my project and it worked flawlessly. I linked both, the `src/module.ts` and the `dist/module.cjs`. I don't know if that is how that is supposed to be tested but it worked.

Note:  When I tried to run `yarn run prepack` without building the playground environment first, it threw some error that said that it couldn't find some typescript configuration files. I don't know if the playground environment should be built before publishing a release or not, but that seemed relevant.

**Comment by Baroshem** [comment]
Hey guys, @dimitrio-m created a PR with a fix (and general refactor - thanks for that! 💚)

Could you check if the error persists on 0.5.0 version?

**Comment by dimitrio-m** [comment]
Hello @Baroshem ! I'm glad that the PR got merged! I would like to help you maintain this module :smile: 

Regarding the fix, I tried importing it in a new project and it worked. I also tried importing it in a new project following the [Authoring Nuxt Layers Guide](https://nuxt.com/docs/guide/going-further/layers) and it worked there too.

**Comment by Baroshem** [comment]
@SaulAbreu @fsyntax 

Could you check if it works right now?

**Comment by evan959** [comment]
it's not work,this my dependencies
```
"nuxt": "^3.11.2",
"vue": "^3.4.21",
"vue-router": "^4.3.0"
```

**Comment by Baroshem** [comment]
Hey @evan959 could you please create a new issue with reproduction steps or repo?

**Comment by evan959** [comment]
ok, @Baroshem   I created [new issuse](https://github.com/Baroshem/nuxt-medusa/issues/43), please take a look
