### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] Cannot find module './lib/axios'

### ISSUE THREAD

**Issue by evan959** [Baroshem/nuxt-medusa#43]
### Version

nuxt-medusa : v0.5.0
nuxt: v3.11.2
### Steps to reproduce
I created  a new nuxt project with the following command
```
npx nuxi init test-nuxt-app
```
And I installed nuxt-medusa according to [this page](https://nuxt.com.cn/modules/medusa).
I run the project
```
pnpm run dev
```
I accessed http://localhost:3000/ through the browser, and the project started to throw errors.
```
[nuxt] [request error] [unhandled] [500] Cannot find module './lib/axios'
```

**Comment by Baroshem** [comment]
Hey, thanks for reporting this issue. I think it is related to how medusa package is optimized for Vite.

Are you using any of NuxtMedusa composables or is this error appearing right after importing the module into nuxt config?

**Comment by evan959** [comment]
> Hey, thanks for reporting this issue. I think it is related to how medusa package is optimized for Vite.
> 
> Are you using any of NuxtMedusa composables or is this error appearing right after importing the module into nuxt config?

I encountered the error right after importing the module into the Nuxt config. I haven't used any NuxtMedusa composables.

**Comment by Baroshem** [comment]
Is this just a regular Hello World app? Could you tell me what is your nuxt.config and what rendering mode do you use?

**Comment by evan959** [comment]
Yep, it's just a hello world project.this is my nuxt.config.js content
````
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["nuxt-medusa"],
});
````

**Comment by evan959** [comment]
I add the config in my nuxt.config.js,add I install this dependencies,it's work!
````
  vite: {
    optimizeDeps: {
      include: ["axios","cross-env","qs","retry-axios","uuid"],
    },
  },
````

**Comment by Baroshem** [comment]
Glad that it works but the problem is that it should be working already. Maybe we need to push all these deps as a part of the module configuration to not have this situation for the users in the future

      config.optimizeDeps.include.push('@medusajs/medusa-js', 'axios')

**Comment by evan959** [comment]
yes, Thank you for your help. I can close the issue now.
