### ISSUE TITLE
Question About Handling Custom Endpoints (Medusa Server) on StoreFront 

### ISSUE THREAD

**Issue by paulootavio** [Baroshem/nuxt-medusa#48]
Hi,

I hope you're doing well.

I have a question regarding handling custom endpoints on my storefront. I’ve developed a custom shipping rate calculator but couldn’t find any information in the documentation about how to integrate or use custom endpoints on my Medusa server.

Could you provide guidance on this?

Thank you in advance for your help!

Best regards,

**Comment by Baroshem** [comment]
Heyo, nice work!

For that, I think you would need to stick to traditional Nuxt api/server approach that is described here https://nuxt.com/docs/guide/directory-structure/server

**Comment by paulootavio** [comment]
It worked, I looked at the documentation and managed to make the request for medusa js in a custom way and within the storefront.

thank you very much

**Comment by Baroshem** [comment]
Glad I could help! If your project with Nuxt and Medusa will be live and public, please let me know so that I could share it as a case study :)

**Comment by paulootavio** [comment]
> Glad I could help! If your project with Nuxt and Medusa will be live and public, please let me know so that I could share it as a case study :)
> 
> Happy Coding!

Sure,I started developing an ecommerce because I work with a client who uses VTEX (and i want a deepdive about it).
Medusa has a lot to offer customers as an indoor solution but with a beautiful boilerplate. I intend to help Medusa with new features that they do not have in their portfolio today and there is also a lack of practical examples of implementation.

That's why I decided to make one and release it from end to end.

oh about the solution I will have to change the approach, to create manual shipment I cannot dynamically create the value... so I will create the fullfilment from scratch

let me know if i can help in something

**Comment by Baroshem** [comment]
I see. If you are interested in contributing, I think the bast would be if, during development of your project, you would see that there is something missing or just not right, please let me know then so that together we could make it better :)
