### ISSUE TITLE
admin token is added to public runtime config

### ISSUE THREAD

**Issue by pi0** [Baroshem/nuxt-medusa#7]
Hi. Checking code, `apiKey` is directly added to public runtime config (https://github.com/Baroshem/nuxt-medusa/blob/ab120ac4ad45f1af35792a4bfd28fa76e727c24c/src/module.ts#L25) which i assume is an admin token. While client js supports it, isn't it with editing permissions?

**Comment by Baroshem** [comment]
Hey Pooya, thanks for noticing that! 

I will take a look at it and probably add it to the private config instead :)

**Comment by runyasak** [comment]
I've created a PR for this issue.
Please, check out my code: #10

**Comment by runyasak** [comment]
Should we use [privateRuntimeConfig](https://nuxtjs.org/docs/directory-structure/nuxt-config/#privateruntimeconfig) to solve this issue?

**Comment by Baroshem** [comment]
Hey, 

You wiuld have to check because private runtime config is not accessible from the frontend usually. Maybe we would need to inform users that if they want to use apiKey they have to use the server utility.

But medusa client normally accepts apiKey so it would be against it. I have to think about it.

I would say that for now it is not a security problem but I will take a look at it in a few days for the next version.

Let me know about your opinion on this :)

**Comment by runyasak** [comment]
> Hey,
> 
> You wiuld have to check because private runtime config is not accessible from the frontend usually. Maybe we would need to inform users that if they want to use apiKey they have to use the server utility.
> 
> But medusa client normally accepts apiKey so it would be against it. I have to think about it.
> 
> I would say that for now it is not a security problem but I will take a look at it in a few days for the next version.
> 
> Let me know about your opinion on this :)

Thank you for more knowledge. I got more points from this.

I can't figure out another way without storing the API key in the server, using their utility, if you don't want it exposed.

If you have a good solution, please let me know, really want to learn from your project. 😂

Thank you so much. 😁

**Comment by Baroshem** [comment]
@runyasak 

Sorry for no contact on my side. I was quite busy with other tasks this week. 

Coming back to the topic. I would recommend to implement an approach where apiKey is only to runtime config private and accessible by the server utility or plugin (server only). 

This might be different approach from what Medusa client is delivering but I would prefer to deliver users a safer approach (while apiKey will still be accessible in the server side hidden from the frontend code)

**Comment by Baroshem** [comment]
Hey do you mean this? 

https://nuxt-medusa-tailwind.vercel.app/

**Comment by Baroshem** [comment]
I also have the module docs deployed here -> https://nuxt-medusa.vercel.app/. Not sure what do you mean by that @pi0

**Comment by Baroshem** [comment]
Ah, so I dont have that. 

I think we can actually remove it from the runtime config and just add it to private for usage in server utility where this will be hidden.

What do you think @pi0 ?

**Comment by pi0** [comment]
That would be nice to be done (this seems an important issue not exposing adding token!)

**Comment by pi0** [comment]
Any update on this?

**Comment by runyasak** [comment]
> I was hoping for some community contribution by @runyasak 😉
> 
> If you wont answer in the upcoming days, I will develop this feature
> 
> @pi0 

@Baroshem  Sorry, for my late response. And thank you for waiting me.

As far as I know, private runtime config would be a good choice for this issue.

I will contribute soon by today.

Thank you so much again. 😁

**Comment by runyasak** [comment]
@Baroshem I've submitted a new PR for private config.
I'm not sure that it would be your expectation or not. Please check out and review my new PR: #17 😁

**Comment by Baroshem** [comment]
Released with 0.4.0 :)

Thanks for the contribution!
