### ISSUE TITLE
Implicit `defu` dependency

### ISSUE THREAD

**Issue by pi0** [Baroshem/nuxt-medusa#8]
Instead of ignoring `defu` in [build.config](https://github.com/Baroshem/nuxt-medusa/blob/ab120ac4ad45f1af35792a4bfd28fa76e727c24c/build.config.ts#L4) (and other dependencies) you need to explicitly add them to `dependencies` field of module package.

**Comment by Baroshem** [comment]
Thanks, will do that!

**Comment by pi0** [comment]
Thanks. For the context it fixes future issues with pnpm (without shamefully hoist enabled) and also linked layers.
